### ISSUE TITLE
Deprecation notice for Ruby 2.7 is extremely and overly aggressive

### ISSUE THREAD

**Issue by henrikbjorn** [ViewComponent/view_component#1608]
### Steps to reproduce

Use ruby 2.7

### Expected behavior

I expected to not get flooded in my test runs with deprecation notice for ruby 2.7

I suppose I can keep using the 2.x releases for Ruby 2.7 until I am ready to upgrade to ruby 3.x. Me holding off on a future upgrade should not get the logs absolutely spammed with the deprecation message.

Also I suspect the spec for the gem can lists its minium ruby version.

### Actual behavior

Test logs are absolutely flooded with the message `DEPRECATION WARNING: Support for Ruby versions < 2.7.0 will be removed in v3.0.0` since the deprecation is done for every single compilation that is done with a view component.

### System configuration
**Rails version**:

6.1

**Ruby version**:

2.7

**Gem version**:

2.78.0

**Comment by boardfish** [comment]
Here's the [culprit method](https://github.com/ViewComponent/view_component/compare/v2.71.0...v2.73.0#diff-fa28fa6e2d5f267384e7793b855281451a46b8437431867871a298fc52fe4940R36-R38). It might be good to make it so that this warning gets raised only on load.

A failing test should help us to make this change, so I welcome you to follow the steps in our [contributing guide](https://github.com/ViewComponent/view_component/blob/main/docs/CONTRIBUTING.md#reporting-bugs) if you've got the time. Thanks for reporting this issue!
