### ISSUE TITLE
Rename `ViewComponent` to `View`

### ISSUE THREAD

**Issue by joeldrapper** [ViewComponent/view_component#1834]
Hey everyone 👋 

I own the Ruby gem [`view`](https://rubygems.org/gems/view) and would like to offer it to the ViewComponent community if you're interested.

With the `view` gem, you could safely use the `View` namespace and provide a `View::Component` class instead of the current `ViewComponent::Base`. We could also talk about “View components” rather than “ViewComponent components”.

Of course you could alias `ViewComponent::Base` to `View::Component`, etc. for backward compatibility. I also think the existing domain name and branding will continue to be appropriate if the new name is adopted.

Additionally, an update to the `view_component` gem could automatically replace `view_component` with `view` in the user’s `Gemfile`, and all maintained versions could be pushed to the new gem to make the transition as seamless as possible.

If the community is interested, let me know and I can transfer ownership.

**Comment by Spone** [comment]
It's a clever idea and I like how `View::Component` reads.
I'm a bit afraid that `view` is a very generic name for a gem, though.
I'm all for considering this for V4, but we have to carefully weigh the pros and cons.
Let's see what the others think! :eyes:

**Comment by boardfish** [comment]
Thanks for offering that to us @joeldrapper! I think it could be cool, but as @Spone says, we'll want to be careful about how we adopt it. In particular, this line got me thinking:

> We could also talk about “View components” rather than “ViewComponent components”.

I guess my main concerns are around SEO and referring to the gem consistently. I think we would want to hang onto ViewComponent as a name, because it's distinct enough that it's good for SEO – as it stands, when you search for "ViewComponent", you might see some stuff about .NET and Razor, but ViewComponent is doing well in the results. If folks started searching for "view ruby gem", "view rails gem", "view rails", and the like, they might get results relating to things like how to list installed Ruby gems, or Action View. There's a bit of a question around whether using `view` as the gem name would lead folks to conflate that with ViewComponent as the name of the tool we're providing.

Thinking about things through this lens feels important, as it'll influence new adopters' first impressions of ViewComponent. I feel as though we should break down what that looks like now and what it would look like with `view` in the mix.

**Comment by joeldrapper** [comment]
Totally understand this will take some careful consideration There’s no rush at all from me; just give me a shout if/when you want it.

> I'm a bit afraid that `view` is a very generic name for a gem, though.

Is the concern here that Ruby core might use the `View` namespace in the future? I can’t imagine anyone else will use it unless they’re shipping a gem named `view`. 🤔 

Re: SEO, we already rank pretty well for "view Ruby gem", though not top 10. I don’t see us losing the "viewcomponent" or "view component" SERPs, especially if the title continues to include those words and people will continue linking phrases like "View components" to the website.

**Comment by camertron** [comment]
This is very kind of you @joeldrapper, thanks for offering!

Personally, I'm not sure what we get from renaming the project, aside from avoiding awkward language. By itself, that doesn't feel like a particularly big win to me. Internally we already say "view components" and largely avoid the clumsy language of `ViewComponent components`. We don't use any other component library in Ruby, so there is no need to distinguish between them. I'd be curious to hear if this is a problem in the wider community though.

> Is the concern here that Ruby core might use the `View` namespace in the future?

Oh maybe, I hadn't thought of that 🤔 My concern is more that "view" is a very generic name that doesn't describe what the framework does. It has to do with views, but specifically the component part of the view layer. Thanks to React, most devs have a pretty specific idea of what a "component" is, and I think that connotation very much helps people understand immediately what ViewComponent does.

I think a stronger case could be made if there were two or more projects that could be united under the `View::` namespace.

**Comment by reeganviljoen** [comment]
@camertron @joeldrapper I feel this issue has been discussed adequately and has come to its resolution so I will close this issue, if any further discussion is needed don't be afraid to re-open this issue
