### ISSUE TITLE
Rename `helpers` to `globals`

### ISSUE THREAD

**Issue by reeganviljoen** [ViewComponent/view_component#1836]
Hey ViewCompoent community  👋

# The problem 
storing the global view_context in a method called helpers is unintuitive for beginners, and even for experienced developers a method should describe what it does, which helpers barely does and not well at it. I was thinking a name like globals would accurately describe what it does and maybe even make it more of a thought process before coupling global state into a component which is generally a bad idea and should be used as a lasts resort.

I know that this would break a lot of existing code so I propose that this change be looked at for version 4

**Comment by reeganviljoen** [comment]
@Spone @boardfish @BlakeWilliams @camertron any thoughts , all opinions welcome

**Comment by camertron** [comment]
Hey @reeganviljoen, thanks for bringing this up! I believe it's called `#helpers` is to mimic Rails, which [introduced the `#helpers` method in controllers in Rails 5](https://www.bigbinary.com/blog/rails-add-helpers-method-to-ease-usage-of-helper-modules-in-controllers#new-way-to-call-helper-methods-in-rails-5). In fact, the [original implementation](https://github.com/rails/rails/pull/24866/files#diff-6b77af243a23efcde71c16accfd0b56c643a129fa1a725e5ca1b30e0ee06b994R119) of `#helpers` in Rails simply returned `@view_context`, just like we're doing in ViewComponent.

I'm not sure `#globals` is the right name, since the idea behind `#helpers` is to make it obvious how to call helper methods in component classes. I agree there is more functionality available on the view context than just helpers, but if we'd like to signal that functionality to framework consumers, I would propose adding another method that also returns the view context instead of changing the existing name.

**Comment by reeganviljoen** [comment]
@camertron I get that this is something we are doing to be consistent with rails but I think the context is very different. In controllers and views it makes sense because all state is global state to so the naming makes sense.In ViewComponent however we have local and global state and the name helpers doesn't tell me hey if you need global state look here which as led me to personally experienced people people being confused about the purpose of helpers because the naming is unclear, so many people just dont use and pass in objects as a params , i.e (`current_user` in devise) when its already present in `helpers`

**Comment by reeganviljoen** [comment]
I would however happy keeping `helpers` and maybe adding `globals` as a method that wraps around `helpers` and add a note that `globals` is exactly that but is their for clarity

**Comment by boardfish** [comment]
> so many people just dont use and pass in objects as a params , i.e (`current_user` in devise) when its already present in `helpers`

I would argue that this is a good thing – if you make it easy for folks to do so, then it becomes much clearer that there is a dependency on some `User` object in your component. I can respect that this is a situation where it might be a good decision, though.

Coming back to your reason for this issue, I think you've captured something interesting here – I feel as though folks that are new to the view layer in Rails might not always correlate things like Devise's `current_user` and Rails' `dom_id` with helpers, and until they know that those things are helpers, they might not refer to the `helpers` object to use them.

I wonder if it would be useful to give `NoMethodError` some "did you mean" functionality? So instead of raising a `NoMethodError` for something like `current_user` unchanged, we see if `helpers` would be able to respond to it instead and signal that the developer can do that if they wish?

**Comment by reeganviljoen** [comment]
@boardfish I think that would be very helpful to people who don't know all that much about the view layer

**Comment by camertron** [comment]
@reeganviljoen 

> In controllers and views it makes sense because all state is global state to so the naming makes sense.

I'm not sure I agree with that. My understanding is a new instance of a controller is constructed for every request. You can't call, for example, `#dom_id` in a controller without going through `#helpers`, which is the same for a component. My opinion is that it's a good thing view components work more like controllers because the alternative is mixing in every helper method into every component, which could lead to component methods inadvertently stepping on helper methods, etc.

> many people just dont use and pass in objects as a params

Interesting, so are people calling `helpers.current_user` in the template instead of passing a `User` object to the component's initializer? I'm not sure there's much we can do about that unless we raise an error or something?

> I would however happy keeping helpers and maybe adding globals as a method that wraps around helpers and add a note that globals is exactly that but is their for clarity

If those unfamiliar with the view layer aren't aware that `#dom_id` (for example) is a helper method, what's to say they will know `#dom_id` is a "global" method?

I do hear what you're saying tho about `#helpers` potentially confusing newcomers, and I'd like to address that.

@boardfish

> I wonder if it would be useful to give NoMethodError some "did you mean" functionality? So instead of raising a NoMethodError for something like current_user unchanged, we see if helpers would be able to respond to it instead and signal that the developer can do that if they wish?

I like this idea. Maybe it could be enabled in dev but disabled in prod environments? We do that a lot in primer/view_components to prevent returning 404s in prod because of (relatively) minor UI issues.

**Comment by BlakeWilliams** [comment]
Thanks for the good discussion above y'all, I generally agree that we should keep it `helpers` to stay closer to Rails naming and conventions, but I think this spurred some great conversation. I love the idea of adding a "did you mean" too!

Personally, for V4 I'd want us to consider _removing_ `helpers` as-is and try to prevent folks from `include`ing helpers onto components in favor of a more explicit API like:

```ruby
class MyComponent < ViewComponent::Base
  use_helper :current_user
end
```

The thought being that it's much more explicit about where your data dependencies are coming from, and mocking them in unit tests is significantly easier. I don't have any plans to push that forward at the moment, but just something I've been thinking on.

**Comment by boardfish** [comment]
Now that #1841 has been merged, should we close this and raise a separate issue to discuss @BlakeWilliams' suggestion of changing the helpers API?

**Comment by reeganviljoen** [comment]
@boardfish I think that would be best
