### ISSUE TITLE
Block content passed to partial via yield is rendered twice

### ISSUE THREAD

**Issue by yoshiyoshiharu** [ViewComponent/view_component#2036]
When using partial which accepts block via `<= yield >` in component, block content is rendered twice and escaped.
```erb
<%= render 'block_acceptable_partial' do %>
  <h1>block content</h1>
<% end %>
```
### Steps to reproduce

Here is a link to a repository demonstrating the behavior:
https://github.com/yoshiyoshiharu/view_component_double_rendered_parital_block

### Expected behavior

<img width="210" alt="スクリーンショット 2024-05-29 21 44 29" src="https://github.com/ViewComponent/view_component/assets/54305137/7cd0c62a-43b4-4ec4-892c-674d3de5cb80">

### Actual behavior

<img width="289" alt="スクリーンショット 2024-05-29 21 43 14" src="https://github.com/ViewComponent/view_component/assets/54305137/94912bb6-2501-4100-b658-c8dd9edd3791">

### System configuration
**Rails version**:
3.2.2
**Ruby version**:
7.0.8
**Gem version**:
3.12.1

**Comment by reeganviljoen** [comment]
@yoshiyoshiharu this is consistent with a bug that relates back to how Rails handles captures that causes double renders, I would suggest refraining from passing blocks to render methods in the partial, or otherwise a more experimental fox would be to enable the [capture_compatiabilty_patch](https://viewcomponent.org/known_issues.html#issues-resolved-by-the-optional-capture-compatibility-patch),

**Comment by yoshiyoshiharu** [comment]
@reeganviljoen 
Sorry for not checking the known issues.
After adding `config.view_component.capture_compatibility_patch_enabled = true` to the config file, it works well.
Thank you for letting me know.

If not necessary, please close this issue.
