### ISSUE TITLE
Parameter DSL

### ISSUE THREAD

**Issue by dkniffin** [ViewComponent/view_component#639]
## Feature request

Add a built-in parameter DSL to ViewComponent:

```rb
class Button < ViewComponent::Base
  property :size, 
    type: String, 
    default: "lg", 
    validations: { 
      inclusion: { in: ["sm", "gt", "md"] }
    }

  # lack of `default` value means it's required. 
  # However, if `fallback` is given, it will return that in production environments, so as to avoid exceptions
  property :text, fallback: "Lorem ipsum" 
end
```

### Motivation

@rosendi proposed an idea [here](https://github.com/github/view_component/issues/206#issuecomment-617588434) and [here](https://github.com/github/view_component/issues/206#issuecomment-617588434) for a DSL for defining the attributes for a ViewComponent. I agree with his reason for it: there's a lot of boilerplate that goes into creating a view component. 

In most cases, there's a few things I want to do in `initialize`:
1. Define the parameters coming, whether they are required, and what the default value is
2. Set an instance variable for the value. Most of the time this has the same name as the parameter. A lot of the time I also want to set this in attr_reader (though sometimes I would rather override the value coming in with some behavior to make it smarter)
3. I want to validate that the value is allowed.

The way to do this right now requires repeating the name of the parameter several times (arg in `initialize()`, instance variable, attr_reader). 

Additionally, using ActiveModel::Validations is less than ideal because has potential to raise exceptions in production. I think there's potential for a built-in DSL to leverage ActiveModel::Validation, while still making it safe, by allowing it to raise in a development environment, and in a production environment it can use the fallback values.

This would also avoid the issue of `def initialize` needing to sometimes take many many parameters, which makes the line very very long.

**Comment by dzunk** [comment]
Interested in the outcome of this discussion. FWIW, we use [dry-initializer](https://dry-rb.org/gems/dry-initializer/3.0/) in all our view components for this exact purpose.

**Comment by joelhawksley** [comment]
@dkniffin thanks for raising this issue!

I like the API you've proposed! However, I agree with @dzunk's approach to use `dry-initializer` for this functionality, as I'm wary of having ViewComponent be the arbiter of such a DSL. 

Perhaps this might be worth an update to the documentation? I'd be fine with recommending `dry-initializer`.

**Comment by pinzonjulian** [comment]
Rails already has a couple of ways to enhance the experience of initializing objects that could be used in ViewComponent. 

## ActiveModel attribute assignment

https://api.rubyonrails.org/classes/ActiveModel/AttributeAssignment.html

You could use this for a lightweight way of reducing boilerplate

## ActiveModel::Attributes

https://edgeapi.rubyonrails.org/classes/ActiveRecord/Attributes/ClassMethods.html#method-i-attribute

You can include this module in any object. 

This is probably much closer to what you are looking for. The only issue with this is that it isn't yet a public interface in rails but may be available soon

https://twitter.com/rafaelfranca/status/1361470266782662656?s=20

**Comment by thomasklemm** [comment]
For reference, here's [another example](https://github.com/palkan/view_component-contrib#hanging-initialize-out-to-dry) using [dry-initializer](https://dry-rb.org/gems/dry-initializer).

**Comment by Sorc96** [comment]
I can also recommend `dry-initializer`. Defining simple initializers and attr_readers is one of the few annoying pieces of boilerplate I find myself writing very often. I recently started using dry-initializer for my view_components and it fits perfectly.

There is, however, a caveat when rendering collections using `with_collection`. Because of how dry-initializer works, the component thinks it doesn't accept the collection parameter. I can explain how I have been able to fix this for anybody who encounters the same problem.

`ViewComponent::Base` checks the parameters of `initialize` to see if they include the collection parameter. `initialize_parameters` is used to get the parameters, returning an array of pairs with the type and name of the parameter. With `dry-initializer` , we only get `[[:rest, :args]]` instead of the individual parameters. I decided to change `initialize_parameters` to take `dry-initializer` into account. This is what my base class looks like:

```ruby
class ApplicationComponent < ViewComponent::Base
  extend Dry::Initializer

  def self.initialize_parameters
    # Get only options (keyword parameters) from the dry_initializer belonging to this class.
    options = dry_initializer.options
    if options.empty?
      # No options were defined using dry-initializer, default to the original implementation
      super
    else
      # The first element in the pair can be anything, it currently gets thrown away.
      # :keyreq is what we would get from a keyword argument in a regular method,
      # so we can use it for consistency with the original implementation.
      #
      # The second element is the name of the parameter.
      # Since dry-initializer allows mapping an option to an instance variable of a different name,
      # we want to use the source of the option.
      options.map { |option| [:keyreq, option.source] }
    end
  end
end
```

I think we want to disregard params (positional parameters), although the original implementation seems to check positional parameters as well. I am not entirely sure if that is intentional or not. It does not make much sense to me.

Anyway, I hope this saves a few people some trouble. I don't know if it would be possible to make collections work without this patch while not knowing about `dry-initializer`. Of course, it's also possible to choose `dry-initializer` as the official way to do things and add it as a dependency. This would certainly be a major decision, but I'm kind of silently hoping that it would lead more people to the `dry-rb` ecosystem, which is just amazing 😃

**Comment by BlakeWilliams** [comment]
👋 I've been thinking about an attributes API for a while now and opened up https://github.com/github/view_component/pull/963 as a potential path forward to experiment with that.

Thoughts/feedback welcome!

**Comment by joelhawksley** [comment]
Closing as inactive.

**Comment by dkniffin** [comment]
I just learned about this, which is similar: https://github.com/Amba-Health/view_component_attributes I haven't tried it yet
