### ISSUE TITLE
Define component helpers

### ISSUE THREAD

**Issue by BigBigDoudou** [ViewComponent/view_component#930]
### Summary

Define an helper for each component to make them easily usable from the view/controller:

```ruby
class ExampleComponent < ViewComponent::Base
  def initialize(argument, keyword:)
    @argument = argument
    @keyword = keyword
  end

  def call
    tag.div do
      concat(tag.span(@argument))
      concat(tag.span(@keyword))
      concat(content)
    end
  end
end
```

This will *automatically* define the helper `example_component`:

```ruby
# from the view
example_component("Hello", keyword: "World") do
  tag.span("!")
end

# <div>
#   <span>Hello</span>
#   <span>World</span>
#   <span>!</span>
# </div>

# This is equivalent to:
render ExampleComponent.new("Hello", keyword: "World") do
  tag.span("!")
end
```

The main idea is to be closer to other Rails helpers, so a frontend developer uses all components the same way:

```ruby
# view

# a rails helper
form_with user do |f|
  # ...
end

# another rails helper
image_tag(user.avatar_url)

# a view component helper
badge_component(user)
``` 

What do you think? I've started a PR to show what it could look like: https://github.com/github/view_component/pull/929

**Comment by BlakeWilliams** [comment]
👋 Thanks for opening this issue!

I think it might be too soon to consider this option since we're discussing how we name components here: https://github.com/github/view_component/issues/670

**Comment by boardfish** [comment]
I've been working with [view_component-form](/pantographie/view_component-form), so this feels relevant to address - I've noticed the same inconsistency. However, I personally think nothing needs to change here.

The reason Rails' form helpers (`form_with`, `fields_for`, and `fields`) exist is because they wrap the instantiation of a form builder. Instantiating a form builder requires an argument that the developer doesn't need to be concerned with - the current template. Helpers have access to that. ViewComponents don't tend to take this extra arguments because they are rendered to the current template using the `render` helper, so helper methods that render ViewComponents themselves become redundant.

There's probably a way to define these helper methods from within your `ApplicationComponent`, but I don't think I would recommend doing that for the sole purpose of making your method calls look consistent.

**Comment by peteryates** [comment]
If it's of any use in the [GOV.UK Components](https://govuk-components.netlify.app/) lib we [map components to helpers](https://github.com/DFE-Digital/govuk-components/blob/main/app/helpers/govuk_components_helper.rb) so they can be used via `render` or the helper, depending on preference.

**Comment by collimarco** [comment]
I think that it would be useful to reopen this discussion.

Related:
https://github.com/ViewComponent/view_component/discussions/1922

Using helper notation seems more natural and easier to read/write.

**Comment by collimarco** [comment]
Here's the solution that i finally used:

https://answers.abstractbrain.com/using-rails-helpers-x-component-for-rendering-viewcomponents

I really like it and I don't see any downsides. Feel free to merge it with ViewComponents if you like it.
